// Generated by CoffeeScript 1.8.0
(function() {
  var app, cluster, cpu, debug, server, _i, _len, _ref;

  debug = require("debug")("app");

  app = require("./server/index");

  cluster = require("cluster");

  app.set("port", process.env.PORT || 3000);

  if (cluster.isMaster) {
    _ref = require('os').cpus();
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      cpu = _ref[_i];
      cluster.fork();
    }
  } else {
    server = app.listen(app.get("port"), function() {
      return console.log("Cluster listening on port " + server.address().port);
    });
  }

}).call(this);
