// Generated by CoffeeScript 1.8.0
(function() {
  module.exports = {
    db: process.env.MONGODB || process.env.MONGOLAB_URI || process.env.MONGOHQ_URL || "mongodb://localhost:27017/membership",
    sessionSecret: process.env.SESSION_SECRET || "vpn",
    xero: {
      key: process.env.XERO_KEY || "",
      secret: process.env.XERO_SECRET || "",
      rsa: process.env.XERO_RSA || ""
    },
    mailgun: {
      user: process.env.MAILGUN_USER || "vpn.ht",
      password: process.env.MAILGUN_PASSWORD || ""
    },
    vpnht: {
      url: process.env.VPNHT_URL || "http://fr01.vpn.ht:8080",
      key: process.env.VPNHT_APIKEY || "",
      secret: process.env.VPNHT_APISECRET || ""
    },
    bitpayOptions: {},
    stripeOptions: {
      apiKey: process.env.STRIPE_KEY || "",
      stripePubKey: process.env.STRIPE_PUB_KEY || "",
      defaultPlan: "free",
      plans: ["weekly", "monthly", "yearly", "lifely"],
      planData: {
        weekly: {
          name: "Weekly",
          price: 1.99
        },
        monthly: {
          name: "Monthly",
          price: 4.99
        },
        yearly: {
          name: "Yearly",
          price: 39.99
        },
        lifely: {
          name: "Lifetime",
          price: 299.99
        }
      }
    },
    googleAnalytics: process.env.GOOGLE_ANALYTICS || ""
  };

}).call(this);
