// Generated by CoffeeScript 1.8.0
(function() {
  var mongoose, txnSchema;

  mongoose = require("mongoose");

  txnSchema = new mongoose.Schema({
    customerId: String,
    type: String,
    amount: String,
    data: String
  });

  module.exports = mongoose.model("Txn", txnSchema);

}).call(this);
