// Generated by CoffeeScript 1.8.0
(function() {
  var User, mailgunApiTransport, moment, nodemailer, request, restify, secrets;

  secrets = require("../config/secrets");

  restify = require("restify");

  nodemailer = require("nodemailer");

  mailgunApiTransport = require("nodemailer-mailgunapi-transport");

  User = require("../models/user");

  moment = require("moment");

  request = require("request");

  exports.remove = function(customerId, callback) {
    return User.findOne({
      "stripe.customerId": customerId
    }, function(err, user) {
      if (err) {
        return callback(err, false);
      }
      if (!user) {
        return callback(false, true);
      } else {
        user.stripe.plan = 'free';
        user.expiration = new Date();
        return user.save(function(err) {
          if (err) {
            return callback(err, false);
          }
          console.log("user: " + user.username + " subscription was successfully cancelled");
          return callback(false, true);
        });
      }
    });
  };

  exports.activate = function(customerId, plan, billingType, callback) {
    return User.findOne({
      "stripe.customerId": customerId
    }, function(err, user) {
      if (err) {
        return callback(err, false);
      }
      if (!user) {
        return callback(false, true);
      } else {
        return request.get({
          url: "https://billing.vpn.ht/pt_ipn.php?email=" + user.email
        }, function(error, response, body) {
          return callback(false, true);
        });
      }
    });
  };

}).call(this);
