// Generated by CoffeeScript 1.8.0
(function() {
  "use strict";
  exports.isAuthenticated = function(req, res, next) {
    if (req.isAuthenticated()) {
      return next();
    }
    return res.redirect(req.redirect.auth);
  };

  exports.isUnauthenticated = function(req, res, next) {
    if (!req.isAuthenticated()) {
      return next();
    }
    return res.redirect(req.redirect.auth);
  };

}).call(this);
