// Generated by CoffeeScript 1.8.0
(function() {
  "use strict";
  module.exports = {
    notFound: function(req, res, next) {
      var err;
      err = new Error("Not Found");
      err.status = 404;
      return next(err);
    },
    development: function(err, req, res, next) {
      var customError;
      customError = {
        message: err.message,
        error: err
      };
      res.status(err.status || 500);
      return res.format({
        json: function() {
          return res.json(customError);
        },
        html: function() {
          return res.render("error", {
            err: customError
          });
        }
      });
    },
    production: function(err, req, res, next) {
      var customError;
      customError = {
        message: err.message || "Not Found",
        error: false
      };
      res.status(err.status || 500);
      return res.format({
        json: function() {
          return res.json(customError);
        },
        html: function() {
          return res.render("error", customError);
        }
      });
    }
  };

}).call(this);
