// Generated by CoffeeScript 1.8.0
(function() {
  var Txn, User;

  Txn = require("../models/txn");

  User = require("../models/user");

  module.exports = {
    add: function(customerId, plan, billingType, callback) {
      var transaction;
      transaction = new Txn({
        customerId: customerId,
        plan: plan,
        billingType: billingType
      });
      return transaction.save(function(err, transaction) {
        if (err) {
          return callback(err, false);
        }
        return callback(false, transaction);
      });
    },
    update: function(txnId, status, data, callback) {
      return Txn.findOne({
        "_id": txnId
      }, function(err, txn) {
        if (err) {
          return callback(err, false);
        }
        if (!txn) {
          return callback(false, false);
        } else {
          txn.status = status;
          txn.data = data;
          return txn.save(function(err, txn) {
            if (err) {
              return callback(err, false);
            }
            return callback(false, txn);
          });
        }
      });
    },
    prepare: function(txnId, callback) {
      return Txn.findOne({
        "_id": txnId
      }, function(err, txn) {
        if (err) {
          return callback(err, false);
        }
        if (!txn) {
          return callback(false);
        } else {
          if (txn.billingType === 'monthly') {
            if (txn.billingType === 'paypal') {
              return callback('payments/paypal_monthly_pt');
            } else if (txn.billingType === 'bitpay') {
              return callback('payments/bitpay_monthly_pt');
            } else if (txn.billingType === 'okpay') {
              return callback('payments/okpay_monthly_pt');
            }
          } else {
            if (txn.billingType === 'paypal') {
              return callback('payments/paypal_yearly');
            } else if (txn.billingType === 'bitpay') {
              return callback('payments/bitpay_yearly');
            } else if (txn.billingType === 'okpay') {
              return callback('payments/okpay_yearly');
            }
          }
        }
      });
    }
  };

}).call(this);
