// Generated by CoffeeScript 1.8.0
(function() {
  var Txn;

  Txn = require("../models/txn");

  exports.add = function(customerId, plan, billingType, data, callback) {
    var transaction;
    transaction = new Txn({
      customerId: customerId,
      plan: plan,
      billingType: billingType,
      data: JSON.stringify(data)
    });
    return transaction.save(function(err, transaction) {
      if (err) {
        return callback(err);
      }
      return callback(transaction);
    });
  };

}).call(this);
