// Generated by CoffeeScript 1.8.0
(function() {
  "use strict";
  var secrets;

  secrets = require("../config/secrets");

  module.exports = function(req, res, next) {
    res.locals.path = req.path;
    res.locals.googleAnalytics = secrets.googleAnalytics;
    return next();
  };

}).call(this);
