// Generated by CoffeeScript 1.8.0
(function() {
  var ips, _;

  ips = require("../config/ips");

  _ = require("lodash");

  exports.isConnected = function(ip, callback) {
    if (_.indexOf(ips, ip) === -1) {
      return callback(false);
    } else {
      return callback(true);
    }
  };

}).call(this);
